import { Geist, Geist_Mono } from "next/font/google";
import StatusBar from "../components/modules/Statusbar";
import Tooltip from "../components/utils/Tooltip.util";
import { TooltipProvider } from "../scripts/Tooltip.context";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <StatusBar />
                    {children}
            </body>
        </html>
    );
}
